### ISSUE TITLE
REPORTE HILOS WINDOWS FORM PROYECTO

### ISSUE THREAD

**Issue by IrvinSanchez-dev** [SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-topicos_a-4bs-idm#1]
[PRACTICA HILOS EN WINDOWS FORM PROYECTO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-9-practica-hilos-windows-form-topicos_a-4bs-idm/files/15124854/PRACTICA.HILOS.EN.WINDOWS.FORM.PROYECTO.pdf)

INTEGRANTES DE EQUIPO:
ROSAS GARCIa MARCO URIEL
CRUZ CRUZ DIEGO
JIMENEZ SANCHEZ IRVIN

**Comment by Kevinosorio77** [comment]
De acuerdo ala rubrica el trabajo cumple con una buena estructura , entendible, indicaciones y con el procedimiento de las imágenes 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
